# Generated by Django 5.1.1 on 2024-10-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokabeznazvania',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='pokabeznazvania',
            name='message',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='pokabeznazvania',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
